/* sdk_config for IMU BLE peripheral: TWI + app_timer + S130 */

#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

#define NRF_LOG_ENABLED 0
#define NRF_LOG_USES_RTT 1

#define PERIPHERAL_RESOURCE_SHARING_ENABLED 0

#define CLOCK_ENABLED 1
#define CLOCK_CONFIG_XTAL_FREQ NRF_CLOCK_XTALFREQ_Default
#define CLOCK_CONFIG_LF_SRC 1
#define CLOCK_CONFIG_IRQ_PRIORITY 3

#define TWI_ENABLED 1
#define TWI0_ENABLED 1
#define TWI0_USE_EASY_DMA 0
#define TWI1_ENABLED 0
#define TWI_DEFAULT_CONFIG_FREQUENCY 26738688 /* 100 kHz */
#define TWI_DEFAULT_CONFIG_CLR_BUS_INIT 0
#define TWI_DEFAULT_CONFIG_HOLD_BUS_UNINIT 0
#define TWI_DEFAULT_CONFIG_IRQ_PRIORITY 3

#define APP_TIMER_ENABLED 1
#define APP_TIMER_WITH_PROFILER 0
#define APP_TIMER_KEEPS_RTC_ACTIVE 0

#define GPIOTE_ENABLED 0
#define UART_ENABLED 0
#define APP_UART_ENABLED 0
#define SPIS_ENABLED 0

#define BLE_NUS_ENABLED 0
#define BLE_NUS_C_ENABLED 0
#define BLE_LBS_ENABLED 0
#define BLE_DB_DISCOVERY_ENABLED 0
#define PEER_MANAGER_ENABLED 0
#define FSTORAGE_ENABLED 0

#define NRF_SDH_ENABLED 0
#define NRF_SECTION_ITER_ENABLED 0

#define SEGGER_RTT_CONFIG_BUFFER_SIZE_UP 512
#define SEGGER_RTT_CONFIG_MAX_NUM_UP_BUFFERS 2
#define SEGGER_RTT_CONFIG_BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_CONFIG_MAX_NUM_DOWN_BUFFERS 2
#define SEGGER_RTT_CONFIG_DEFAULT_MODE 0
#define SEGGER_RTT_CONFIG_MAX_INT_PRIORITY 2

#endif /* SDK_CONFIG_H */
